//
//  SFBuilding.swift
//  FioriCharts
//
//  Created by Xu, Sheng on 7/13/20.
//

import Foundation

class SFBuilding {
    var pucCode: String
    var facility: String
    var bldgCategory: String
    var facilityType: String
    var yearBuilt: Double
    var yearRennovated: Double
    var sqFt: Double
    var eui: Double
    
    init(pucCode: String, facility: String, bldgCategory: String, facilityType: String, yearBuilt: Double, yearRennovated: Double?, sqFt: Double, eui: Double) {
        self.pucCode = pucCode
        self.facility = facility
        self.bldgCategory = bldgCategory
        self.facilityType = facilityType
        self.yearBuilt = yearBuilt
        if let yr = yearRennovated {
            self.yearRennovated = yr
        } else {
            self.yearRennovated = yearBuilt
        }
        
        self.sqFt = sqFt
        self.eui = eui
    }
}

let SFBuildings: [SFBuilding] = [
    SFBuilding(pucCode: "1684", facility: "Moscone Center West", bldgCategory: "Convention Centers", facilityType: "convention facility", yearBuilt: 2002.0, yearRennovated: nil, sqFt: 775000.0, eui: 74.3),
    SFBuilding(pucCode: "XXX", facility: "Moscone Center North & South", bldgCategory: "Convention Centers", facilityType: "convention facility", yearBuilt: 1981.0, yearRennovated: Optional(1992.0), sqFt: 1296000.0, eui: 58.3),
    SFBuilding(pucCode: "102", facility: "Bill Graham Civic Auditorium", bldgCategory: "Performance Halls", facilityType: "performance hall", yearBuilt: 1915.0, yearRennovated: Optional(1989.0), sqFt: 302250.0, eui: 67.8),
    SFBuilding(pucCode: "XXX", facility: "War Memorial Veterans Building & Opera House", bldgCategory: "Performance Halls", facilityType: "performance hall", yearBuilt: 1932.0, yearRennovated: nil, sqFt: 529700.0, eui: 67.1),
    SFBuilding(pucCode: "468", facility: "Davies Symphony Hall / Zellerbach Rehearsal Hall", bldgCategory: "Performance Halls", facilityType: "performance hall", yearBuilt: 1980.0, yearRennovated: nil, sqFt: 229500.0, eui: 55.9),
    SFBuilding(pucCode: "317", facility: "GGP -- Sharon Arts Studio", bldgCategory: "Museums and Art", facilityType: "art/cultural center", yearBuilt: 1888.0, yearRennovated: Optional(1992.0), sqFt: 11376.0, eui: 77.1),
    SFBuilding(pucCode: "378", facility: "Randall Museum", bldgCategory: "Museums and Art", facilityType: "art/cultural center", yearBuilt: 1951.0, yearRennovated: nil, sqFt: 32030.0, eui: 72.3),
    SFBuilding(pucCode: "3", facility: "SOMArts Cultural Center", bldgCategory: "Museums and Art", facilityType: "art/cultural center", yearBuilt: 1906.0, yearRennovated: nil, sqFt: 17844.0, eui: 32.2),
    SFBuilding(pucCode: "302", facility: "Harvey Milk Center for the Arts", bldgCategory: "Museums and Art", facilityType: "art/cultural center", yearBuilt: 1950.0, yearRennovated: Optional(2009.0), sqFt: 23125.0, eui: 28.9),
    SFBuilding(pucCode: "4", facility: "Mission Cultural Center for Latino Arts", bldgCategory: "Museums and Art", facilityType: "art/cultural center", yearBuilt: 1948.0, yearRennovated: nil, sqFt: 32230.0, eui: 28.3),
    SFBuilding(pucCode: "2", facility: "African American Art & Culture Complex", bldgCategory: "Museums and Art", facilityType: "art/cultural center", yearBuilt: 1935.0, yearRennovated: nil, sqFt: 34031.0, eui: 27.9),
    SFBuilding(pucCode: "5", facility: "Bayview Opera House", bldgCategory: "Museums and Art", facilityType: "art/cultural center", yearBuilt: 1888.0, yearRennovated: nil, sqFt: 14000.0, eui: 8.8),
    SFBuilding(pucCode: "1", facility: "Arts Commission Window Site / Gallery", bldgCategory: "Museums and Art", facilityType: "art/cultural center", yearBuilt: 1914.0, yearRennovated: nil, sqFt: 4163.0, eui: 8.7),
    SFBuilding(pucCode: "236", facility: "California Palace of the Legion of Honor", bldgCategory: "Museums and Art", facilityType: "museum", yearBuilt: 1924.0, yearRennovated: Optional(1995.0), sqFt: 117665.0, eui: 282.7),
    SFBuilding(pucCode: "293", facility: "GGP -- Conservatory of Flowers", bldgCategory: "Museums and Art", facilityType: "museum", yearBuilt: 1879.0, yearRennovated: Optional(2003.0), sqFt: 27900.0, eui: 212.2),
    SFBuilding(pucCode: "1333", facility: "Asian Art Museum", bldgCategory: "Museums and Art", facilityType: "museum", yearBuilt: 1917.0, yearRennovated: Optional(2003.0), sqFt: 185000.0, eui: 194.0),
    SFBuilding(pucCode: "237", facility: "De Young Museum", bldgCategory: "Museums and Art", facilityType: "museum", yearBuilt: 2005.0, yearRennovated: nil, sqFt: 292500.0, eui: 180.1),
    SFBuilding(pucCode: "697", facility: "California Academy of Sciences", bldgCategory: "Museums and Art", facilityType: "museum", yearBuilt: 2008.0, yearRennovated: nil, sqFt: 426000.0, eui: 147.5),
    SFBuilding(pucCode: "292", facility: "Coit Tower", bldgCategory: "Museums and Art", facilityType: "museum", yearBuilt: 1933.0, yearRennovated: Optional(2012.0), sqFt: 5687.0, eui: 54.1),
    SFBuilding(pucCode: "412", facility: "Argonne CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 2001.0, yearRennovated: nil, sqFt: 2500.0, eui: 106.0),
    SFBuilding(pucCode: "2018", facility: "Zaida T Rodriguez Early Education", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 1800.0, eui: 104.4),
    SFBuilding(pucCode: "69", facility: "Earl P Mills Community Center", bldgCategory: "Education", facilityType: "childcare/nursery school", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 15000.0, eui: 61.0),
    SFBuilding(pucCode: "1104", facility: "Noriega CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1951.0, yearRennovated: nil, sqFt: 14700.0, eui: 49.4),
    SFBuilding(pucCode: "723", facility: "Junipero Serra Annex CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1970.0, yearRennovated: nil, sqFt: 5800.0, eui: 50.0),
    SFBuilding(pucCode: "1074", facility: "Commodore Stockton CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 21255.0, eui: 48.8),
    SFBuilding(pucCode: "420", facility: "Jefferson Early Education", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1960.0, yearRennovated: nil, sqFt: 2400.0, eui: 43.9),
    SFBuilding(pucCode: "1014", facility: "John McLaren CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1954.0, yearRennovated: nil, sqFt: 57885.0, eui: 42.7),
    SFBuilding(pucCode: "1910", facility: "Sojourner Truth Child Center", bldgCategory: "Education", facilityType: "childcare/nursery school", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 5184.0, eui: 38.2),
    SFBuilding(pucCode: "820", facility: "Playmates Nursery", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1954.0, yearRennovated: nil, sqFt: 3000.0, eui: 34.8),
    SFBuilding(pucCode: "1133", facility: "Leola M Havard Early Education", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1969.0, yearRennovated: nil, sqFt: 74100.0, eui: 32.3),
    SFBuilding(pucCode: "416", facility: "Theresa Mahler CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1943.0, yearRennovated: nil, sqFt: 5339.0, eui: 31.7),
    SFBuilding(pucCode: "414", facility: "Mission CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 4100.0, eui: 29.9),
    SFBuilding(pucCode: "1911", facility: "MLK Child Care Center", bldgCategory: "Education", facilityType: "childcare/nursery school", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 7409.0, eui: 24.8),
    SFBuilding(pucCode: "1131", facility: "Tule Elk Park CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1923.0, yearRennovated: nil, sqFt: 32000.0, eui: 26.3),
    SFBuilding(pucCode: "1019", facility: "San Miguel CDC", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1929.0, yearRennovated: Optional(1953.0), sqFt: 52545.0, eui: 22.2),
    SFBuilding(pucCode: "419", facility: "SFUSD -- SPEd Medical Therapy Unit (Laguna)", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 12400.0, eui: 15.2),
    SFBuilding(pucCode: "1908", facility: "Shorey Childrens Center", bldgCategory: "Education", facilityType: "childcare/nursery school", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 9700.0, eui: 7.7),
    SFBuilding(pucCode: "2034", facility: "Visitacion Valley Family Resource Center", bldgCategory: "Education", facilityType: "Childcare/Nursery School", yearBuilt: 1940.0, yearRennovated: nil, sqFt: 12000.0, eui: 6.4),
    SFBuilding(pucCode: "80", facility: "SFPD Academy", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1966.0, yearRennovated: nil, sqFt: 19332.0, eui: 159.0),
    SFBuilding(pucCode: "1137", facility: "GGP -- Senior Center", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1930.0, yearRennovated: nil, sqFt: 5940.0, eui: 141.7),
    SFBuilding(pucCode: "424", facility: "CCSF -- Ocean Campus", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1940.0, yearRennovated: nil, sqFt: 931000.0, eui: 127.9),
    SFBuilding(pucCode: "721", facility: "Southeast Community Facility and Greenhouses  (5)", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1986.0, yearRennovated: nil, sqFt: 193400.0, eui: 99.8),
    SFBuilding(pucCode: "1037", facility: "CCSF -- Mission Center", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1939.0, yearRennovated: Optional(2005.0), sqFt: 138129.0, eui: 81.5),
    SFBuilding(pucCode: "426", facility: "CCSF -- Downtown Center", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1978.0, yearRennovated: nil, sqFt: 86038.0, eui: 61.5),
    SFBuilding(pucCode: "1797", facility: "Sheriff Community Programs / Five Keys Adult School", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1959.0, yearRennovated: Optional(2004.0), sqFt: 10842.0, eui: 59.7),
    SFBuilding(pucCode: "1962", facility: "CCSF -- Chinatown / North Beach Center", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 2012.0, yearRennovated: nil, sqFt: 157353.0, eui: 37.6),
    SFBuilding(pucCode: "422", facility: "CCSF -- Airport Campus", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1975.0, yearRennovated: nil, sqFt: 27753.0, eui: 31.4),
    SFBuilding(pucCode: "423", facility: "CCSF -- Alemany Campus", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1911.0, yearRennovated: nil, sqFt: 26400.0, eui: 24.7),
    SFBuilding(pucCode: "429", facility: "CCSF -- John Adams Center", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1911.0, yearRennovated: Optional(2009.0), sqFt: 151397.0, eui: 24.3),
    SFBuilding(pucCode: "1162", facility: "CCSF -- Evans Center", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 1984.0, yearRennovated: nil, sqFt: 90000.0, eui: 21.9),
    SFBuilding(pucCode: "2038", facility: "CCSF -- Chinatown / North Beach Annex", bldgCategory: "Education", facilityType: "college/adult education", yearBuilt: 2012.0, yearRennovated: nil, sqFt: 29411.0, eui: 20.7),
    SFBuilding(pucCode: "1102", facility: "Francis Scott Key Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1936.0, yearRennovated: nil, sqFt: 52000.0, eui: 55.5),
    SFBuilding(pucCode: "1098", facility: "Lafayette Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1927.0, yearRennovated: nil, sqFt: 54283.0, eui: 54.8),
    SFBuilding(pucCode: "1088", facility: "Raoul Wallenberg High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1952.0, yearRennovated: nil, sqFt: 62840.0, eui: 62.7),
    SFBuilding(pucCode: "1001", facility: "Ida B Wells High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1910.0, yearRennovated: nil, sqFt: 34300.0, eui: 57.7),
    SFBuilding(pucCode: "1116", facility: "School of the Arts / Academy of Arts and Sciences", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1970.0, yearRennovated: nil, sqFt: 209500.0, eui: 55.1),
    SFBuilding(pucCode: "1394", facility: "Hilltop County Community High / Sunshine Building", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1937.0, yearRennovated: nil, sqFt: 61442.0, eui: 55.1),
    SFBuilding(pucCode: "1099", facility: "George Washington High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1936.0, yearRennovated: nil, sqFt: 228800.0, eui: 53.0),
    SFBuilding(pucCode: "1052", facility: "International Studies Academy at Enola Maxwell", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 108400.0, eui: 48.6),
    SFBuilding(pucCode: "1056", facility: "SF International High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1980.0, yearRennovated: nil, sqFt: 33100.0, eui: 45.3),
    SFBuilding(pucCode: "1051", facility: "Philip and Sala Burton High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1963.0, yearRennovated: nil, sqFt: 230000.0, eui: 44.5),
    SFBuilding(pucCode: "1084", facility: "Gateway High / KIPP San Francisco Bay Academy", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1913.0, yearRennovated: nil, sqFt: 143237.0, eui: 42.0),
    SFBuilding(pucCode: "1064", facility: "John O'Connell High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1999.0, yearRennovated: nil, sqFt: 130091.0, eui: 40.1),
    SFBuilding(pucCode: "1078", facility: "Galileo High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 242400.0, eui: 39.2),
    SFBuilding(pucCode: "1798", facility: "Independence High (Old Laguna Honda)", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1908.0, yearRennovated: nil, sqFt: 30114.0, eui: 37.2),
    SFBuilding(pucCode: "1814", facility: "Downtown High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1936.0, yearRennovated: nil, sqFt: 58760.0, eui: 36.9),
    SFBuilding(pucCode: "1033", facility: "Thurgood Marshall High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1957.0, yearRennovated: nil, sqFt: 149796.0, eui: 34.9),
    SFBuilding(pucCode: "1044", facility: "Mission High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1922.0, yearRennovated: nil, sqFt: 225000.0, eui: 32.7),
    SFBuilding(pucCode: "1021", facility: "June Jordan High / City Arts and Tech High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1957.0, yearRennovated: nil, sqFt: 151600.0, eui: 32.6),
    SFBuilding(pucCode: "1059", facility: "Abraham Lincoln High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1940.0, yearRennovated: nil, sqFt: 330200.0, eui: 31.6),
    SFBuilding(pucCode: "1017", facility: "Balboa High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1928.0, yearRennovated: nil, sqFt: 261700.0, eui: 30.5),
    SFBuilding(pucCode: "1002", facility: "Lowell High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1962.0, yearRennovated: nil, sqFt: 245000.0, eui: 30.2),
    SFBuilding(pucCode: "1035", facility: "Mission Education Center Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1911.0, yearRennovated: nil, sqFt: 27000.0, eui: 113.1),
    SFBuilding(pucCode: "1025", facility: "El Dorado Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1953.0, yearRennovated: nil, sqFt: 30300.0, eui: 99.3),
    SFBuilding(pucCode: "1392", facility: "Claire Lilienthal (K-2 Madison Campus)", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1910.0, yearRennovated: nil, sqFt: 20855.0, eui: 76.0),
    SFBuilding(pucCode: "1012", facility: "Visitacion Valley Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 113600.0, eui: 75.8),
    SFBuilding(pucCode: "1003", facility: "Jose Ortega Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1953.0, yearRennovated: nil, sqFt: 35180.0, eui: 69.6),
    SFBuilding(pucCode: "1107", facility: "Sunset Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1951.0, yearRennovated: nil, sqFt: 40150.0, eui: 69.5),
    SFBuilding(pucCode: "1106", facility: "Robert Louis Stevenson Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1953.0, yearRennovated: nil, sqFt: 47500.0, eui: 64.3),
    SFBuilding(pucCode: "1096", facility: "George Peabody Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 16229.0, eui: 61.7),
    SFBuilding(pucCode: "1046", facility: "Paul Revere Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1928.0, yearRennovated: Optional(1968.0), sqFt: 56400.0, eui: 57.3),
    SFBuilding(pucCode: "1027", facility: "Dr George Washington Carver Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1974.0, yearRennovated: nil, sqFt: 45500.0, eui: 54.5),
    SFBuilding(pucCode: "1071", facility: "Redding Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1917.0, yearRennovated: nil, sqFt: 26100.0, eui: 51.9),
    SFBuilding(pucCode: "1008", facility: "Sunnyside Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1927.0, yearRennovated: nil, sqFt: 30900.0, eui: 51.8),
    SFBuilding(pucCode: "1109", facility: "Ulloa Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1952.0, yearRennovated: nil, sqFt: 53000.0, eui: 51.7),
    SFBuilding(pucCode: "1038", facility: "Buena Vista / Horace Mann", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 68000.0, eui: 50.3),
    SFBuilding(pucCode: "1024", facility: "Hillcrest Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1951.0, yearRennovated: nil, sqFt: 60280.0, eui: 49.9),
    SFBuilding(pucCode: "1028", facility: "Malcolm X Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1957.0, yearRennovated: nil, sqFt: 50800.0, eui: 49.6),
    SFBuilding(pucCode: "1264", facility: "Rooftop Alternative (5-8 Mayeda Campus)", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1997.0, yearRennovated: nil, sqFt: 21000.0, eui: 49.1),
    SFBuilding(pucCode: "1101", facility: "Alamo Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 50420.0, eui: 47.4),
    SFBuilding(pucCode: "1118", facility: "Clarendon Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1962.0, yearRennovated: nil, sqFt: 39500.0, eui: 47.1),
    SFBuilding(pucCode: "1082", facility: "Claire Lilienthal (3-8 Winfield Scott Campus)", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1930.0, yearRennovated: nil, sqFt: 34000.0, eui: 47.0),
    SFBuilding(pucCode: "1100", facility: "Presidio Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1930.0, yearRennovated: nil, sqFt: 140000.0, eui: 46.6),
    SFBuilding(pucCode: "1067", facility: "Civic Center Secondary at John Swett Campus", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1912.0, yearRennovated: nil, sqFt: 29060.0, eui: 46.2),
    SFBuilding(pucCode: "1089", facility: "New Traditions Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 26300.0, eui: 45.9),
    SFBuilding(pucCode: "1377", facility: "George Moscone Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1997.0, yearRennovated: nil, sqFt: 45108.0, eui: 45.0),
    SFBuilding(pucCode: "1105", facility: "A P Giannini Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1954.0, yearRennovated: nil, sqFt: 136392.0, eui: 44.6),
    SFBuilding(pucCode: "2040", facility: "Gateway Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1908.0, yearRennovated: nil, sqFt: 31121.0, eui: 43.9),
    SFBuilding(pucCode: "1005", facility: "Longfellow Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1960.0, yearRennovated: nil, sqFt: 40500.0, eui: 43.3),
    SFBuilding(pucCode: "1110", facility: "Jefferson Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1923.0, yearRennovated: nil, sqFt: 42434.0, eui: 43.2),
    SFBuilding(pucCode: "1086", facility: "Dr William Cobb Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1923.0, yearRennovated: nil, sqFt: 36246.0, eui: 42.6),
    SFBuilding(pucCode: "1111", facility: "Lawton Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1934.0, yearRennovated: nil, sqFt: 64940.0, eui: 42.2),
    SFBuilding(pucCode: "1068", facility: "John Muir Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1928.0, yearRennovated: nil, sqFt: 53500.0, eui: 42.1),
    SFBuilding(pucCode: "1040", facility: "Harvey Milk Civil Rights Academy", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1952.0, yearRennovated: nil, sqFt: 30560.0, eui: 40.9),
    SFBuilding(pucCode: "1055", facility: "Bryant Elementary and CDC", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1969.0, yearRennovated: nil, sqFt: 32500.0, eui: 40.5),
    SFBuilding(pucCode: "1045", facility: "Leonard R Flynn Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1926.0, yearRennovated: nil, sqFt: 52700.0, eui: 40.3),
    SFBuilding(pucCode: "1061", facility: "Bessie Carmichael Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 2000.0, yearRennovated: nil, sqFt: 56358.0, eui: 40.2),
    SFBuilding(pucCode: "1050", facility: "E R Taylor Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1923.0, yearRennovated: nil, sqFt: 56113.0, eui: 40.1),
    SFBuilding(pucCode: "1083", facility: "Rosa Parks Elementary / Raphael Weill CDC", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1927.0, yearRennovated: Optional(1964.0), sqFt: 66900.0, eui: 39.6),
    SFBuilding(pucCode: "1042", facility: "Everett Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1926.0, yearRennovated: nil, sqFt: 155370.0, eui: 39.6),
    SFBuilding(pucCode: "1351", facility: "Argonne Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1997.0, yearRennovated: nil, sqFt: 52000.0, eui: 39.5),
    SFBuilding(pucCode: "1094", facility: "Sutro Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 32860.0, eui: 39.3),
    SFBuilding(pucCode: "1004", facility: "Sheridan Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1975.0, yearRennovated: nil, sqFt: 46335.0, eui: 39.2),
    SFBuilding(pucCode: "1114", facility: "Alice Fong Yu Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1914.0, yearRennovated: nil, sqFt: 59650.0, eui: 38.8),
    SFBuilding(pucCode: "1120", facility: "Marina Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1936.0, yearRennovated: nil, sqFt: 152900.0, eui: 38.7),
    SFBuilding(pucCode: "1036", facility: "James Lick Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1932.0, yearRennovated: nil, sqFt: 116000.0, eui: 37.9),
    SFBuilding(pucCode: "1010", facility: "Commodore Sloat Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1977.0, yearRennovated: nil, sqFt: 59200.0, eui: 37.8),
    SFBuilding(pucCode: "1097", facility: "Roosevelt Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1930.0, yearRennovated: nil, sqFt: 121000.0, eui: 37.4),
    SFBuilding(pucCode: "1075", facility: "Chinese Education Center", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 10580.0, eui: 37.1),
    SFBuilding(pucCode: "1041", facility: "Alvarado Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1926.0, yearRennovated: nil, sqFt: 51700.0, eui: 37.1),
    SFBuilding(pucCode: "1081", facility: "John Yehall Chin Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1914.0, yearRennovated: nil, sqFt: 23100.0, eui: 37.0),
    SFBuilding(pucCode: "1020", facility: "Cleveland Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1911.0, yearRennovated: nil, sqFt: 34000.0, eui: 36.5),
    SFBuilding(pucCode: "1022", facility: "Monroe Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1977.0, yearRennovated: nil, sqFt: 53400.0, eui: 36.5),
    SFBuilding(pucCode: "1123", facility: "Dr Martin Luther King Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1940.0, yearRennovated: nil, sqFt: 72210.0, eui: 36.3),
    SFBuilding(pucCode: "1115", facility: "Herbert Hoover Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1956.0, yearRennovated: nil, sqFt: 132400.0, eui: 35.9),
    SFBuilding(pucCode: "1030", facility: "Dr Charles R Drew Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 55234.0, eui: 35.2),
    SFBuilding(pucCode: "1384", facility: "Tenderloin Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1998.0, yearRennovated: nil, sqFt: 61569.0, eui: 34.6),
    SFBuilding(pucCode: "1011", facility: "Glen Park Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1936.0, yearRennovated: nil, sqFt: 45200.0, eui: 34.3),
    SFBuilding(pucCode: "1130", facility: "Starr King Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1955.0, yearRennovated: nil, sqFt: 49900.0, eui: 34.1),
    SFBuilding(pucCode: "1016", facility: "James Denman Middle / Leadership High", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1940.0, yearRennovated: nil, sqFt: 150900.0, eui: 33.8),
    SFBuilding(pucCode: "1121", facility: "Lakeshore Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1954.0, yearRennovated: nil, sqFt: 56101.0, eui: 33.3),
    SFBuilding(pucCode: "1117", facility: "Rooftop Alternative (K-4 Burnett Campus)", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1952.0, yearRennovated: nil, sqFt: 23300.0, eui: 33.3),
    SFBuilding(pucCode: "1009", facility: "Aptos Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1931.0, yearRennovated: nil, sqFt: 168000.0, eui: 33.2),
    SFBuilding(pucCode: "1029", facility: "Bret Harte Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1954.0, yearRennovated: nil, sqFt: 79000.0, eui: 32.7),
    SFBuilding(pucCode: "1043", facility: "Sanchez Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1927.0, yearRennovated: nil, sqFt: 50500.0, eui: 32.5),
    SFBuilding(pucCode: "1060", facility: "Bessie Carmichael / Filipino Education Ctr (6-8)", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1975.0, yearRennovated: nil, sqFt: 13654.0, eui: 32.3),
    SFBuilding(pucCode: "1125", facility: "Chinese Immersion Elementary at DeAvila", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1926.0, yearRennovated: nil, sqFt: 58582.0, eui: 32.1),
    SFBuilding(pucCode: "1057", facility: "Cesar Chavez Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1926.0, yearRennovated: nil, sqFt: 49100.0, eui: 32.1),
    SFBuilding(pucCode: "1053", facility: "Daniel Webster Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 42800.0, eui: 32.1),
    SFBuilding(pucCode: "1069", facility: "Creative Arts Charter", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1962.0, yearRennovated: nil, sqFt: 33117.0, eui: 31.3),
    SFBuilding(pucCode: "1080", facility: "Garfield Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1979.0, yearRennovated: nil, sqFt: 33800.0, eui: 31.3),
    SFBuilding(pucCode: "1072", facility: "Spring Valley Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1912.0, yearRennovated: nil, sqFt: 50400.0, eui: 31.1),
    SFBuilding(pucCode: "428", facility: "SFUSD -- 940 Filbert St (Yick Wo Elementary)", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1900.0, yearRennovated: Optional(1925.0), sqFt: 37500.0, eui: 30.7),
    SFBuilding(pucCode: "1241", facility: "Jean Parker Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1996.0, yearRennovated: nil, sqFt: 46000.0, eui: 30.3),
    SFBuilding(pucCode: "1129", facility: "Miraloma Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1952.0, yearRennovated: nil, sqFt: 51900.0, eui: 30.2),
    SFBuilding(pucCode: "1013", facility: "Visitacion Valley Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1936.0, yearRennovated: nil, sqFt: 51400.0, eui: 29.9),
    SFBuilding(pucCode: "1023", facility: "SF Community School", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1911.0, yearRennovated: nil, sqFt: 66900.0, eui: 29.6),
    SFBuilding(pucCode: "1079", facility: "Francisco Middle", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1926.0, yearRennovated: nil, sqFt: 104897.0, eui: 29.2),
    SFBuilding(pucCode: "1006", facility: "West Portal Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1927.0, yearRennovated: nil, sqFt: 44700.0, eui: 29.0),
    SFBuilding(pucCode: "125", facility: "SF Public Montessori Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 64500.0, eui: 28.8),
    SFBuilding(pucCode: "1077", facility: "Sherman Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1928.0, yearRennovated: nil, sqFt: 56200.0, eui: 28.5),
    SFBuilding(pucCode: "1039", facility: "Edison Charter Academy Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1927.0, yearRennovated: nil, sqFt: 59200.0, eui: 27.5),
    SFBuilding(pucCode: "1091", facility: "Grattan Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 55420.0, eui: 27.5),
    SFBuilding(pucCode: "1112", facility: "Dianne Feinstein Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 2003.0, yearRennovated: nil, sqFt: 62087.0, eui: 26.4),
    SFBuilding(pucCode: "1062", facility: "Marshall Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1977.0, yearRennovated: nil, sqFt: 34300.0, eui: 24.5),
    SFBuilding(pucCode: "1095", facility: "Frank McCoppin Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 32700.0, eui: 24.3),
    SFBuilding(pucCode: "1034", facility: "Fairmount Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 60960.0, eui: 22.3),
    SFBuilding(pucCode: "1049", facility: "Junipero Serra Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1977.0, yearRennovated: nil, sqFt: 34200.0, eui: 21.7),
    SFBuilding(pucCode: "1128", facility: "Yick Wo Elementary (under modernization)", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1983.0, yearRennovated: nil, sqFt: 26000.0, eui: 20.7),
    SFBuilding(pucCode: "2017", facility: "Gordon J Lau Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1914.0, yearRennovated: Optional(1956.0), sqFt: 63800.0, eui: 19.2),
    SFBuilding(pucCode: "1092", facility: "McKinley Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1977.0, yearRennovated: nil, sqFt: 45160.0, eui: 19.1),
    SFBuilding(pucCode: "1015", facility: "Guadalupe Elementary", bldgCategory: "Education", facilityType: "K-12 School", yearBuilt: 1922.0, yearRennovated: nil, sqFt: 40777.0, eui: 17.7),
    SFBuilding(pucCode: "254", facility: "Ocean View Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 2000.0, yearRennovated: nil, sqFt: 4794.0, eui: 157.5),
    SFBuilding(pucCode: "241", facility: "Chinatown Him Mark Lai Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1921.0, yearRennovated: Optional(1996.0), sqFt: 17858.0, eui: 111.8),
    SFBuilding(pucCode: "265", facility: "Western Addition Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1966.0, yearRennovated: Optional(2008.0), sqFt: 8000.0, eui: 89.2),
    SFBuilding(pucCode: "264", facility: "West Portal Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1939.0, yearRennovated: Optional(2007.0), sqFt: 8010.0, eui: 77.0),
    SFBuilding(pucCode: "45", facility: "Fire Station 38", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1960.0, yearRennovated: nil, sqFt: 13400.0, eui: 78.7),
    SFBuilding(pucCode: "261", facility: "Richmond/Milton Marks Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1914.0, yearRennovated: Optional(2009.0), sqFt: 13900.0, eui: 74.6),
    SFBuilding(pucCode: "248", facility: "Main Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1996.0, yearRennovated: nil, sqFt: 376000.0, eui: 73.6),
    SFBuilding(pucCode: "249", facility: "Marina Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1954.0, yearRennovated: Optional(2007.0), sqFt: 7633.0, eui: 64.7),
    SFBuilding(pucCode: "260", facility: "Presidio Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1921.0, yearRennovated: Optional(2011.0), sqFt: 10205.0, eui: 64.6),
    SFBuilding(pucCode: "238", facility: "Bayview/Anna E. Waden Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 2012.0, yearRennovated: nil, sqFt: 9527.0, eui: 64.4),
    SFBuilding(pucCode: "256", facility: "Park Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1909.0, yearRennovated: Optional(2011.0), sqFt: 8060.0, eui: 62.7),
    SFBuilding(pucCode: "259", facility: "Potrero Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1951.0, yearRennovated: Optional(2010.0), sqFt: 5428.0, eui: 62.3),
    SFBuilding(pucCode: "255", facility: "Ortega Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 2011.0, yearRennovated: nil, sqFt: 9300.0, eui: 60.1),
    SFBuilding(pucCode: "252", facility: "Noe Valley/Sally Brunn Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1916.0, yearRennovated: Optional(2008.0), sqFt: 6096.0, eui: 58.7),
    SFBuilding(pucCode: "1928", facility: "Ingleside Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 2009.0, yearRennovated: nil, sqFt: 6100.0, eui: 58.2),
    SFBuilding(pucCode: "1915", facility: "Portola Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 2009.0, yearRennovated: nil, sqFt: 6427.0, eui: 58.1),
    SFBuilding(pucCode: "251", facility: "Mission Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1916.0, yearRennovated: Optional(1999.0), sqFt: 10479.0, eui: 56.6),
    SFBuilding(pucCode: "262", facility: "Sunset Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1918.0, yearRennovated: Optional(2007.0), sqFt: 9434.0, eui: 54.6),
    SFBuilding(pucCode: "239", facility: "Anza Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1932.0, yearRennovated: Optional(2011.0), sqFt: 8222.0, eui: 52.8),
    SFBuilding(pucCode: "1825", facility: "Bernal Heights Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1940.0, yearRennovated: Optional(2010.0), sqFt: 8777.0, eui: 52.2),
    SFBuilding(pucCode: "263", facility: "Visitacion Valley Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 2011.0, yearRennovated: nil, sqFt: 9945.0, eui: 52.1),
    SFBuilding(pucCode: "250", facility: "Merced Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1958.0, yearRennovated: Optional(2011.0), sqFt: 5832.0, eui: 47.5),
    SFBuilding(pucCode: "257", facility: "Parkside Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1951.0, yearRennovated: Optional(2010.0), sqFt: 6822.0, eui: 41.9),
    SFBuilding(pucCode: "243", facility: "Excelsior Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1967.0, yearRennovated: Optional(2005.0), sqFt: 8322.0, eui: 40.6),
    SFBuilding(pucCode: "253", facility: "North Beach Branch Library (Old Location)", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1959.0, yearRennovated: nil, sqFt: 8455.0, eui: 40.4),
    SFBuilding(pucCode: "244", facility: "Glen Park Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 2007.0, yearRennovated: nil, sqFt: 7185.0, eui: 39.9),
    SFBuilding(pucCode: "242", facility: "Eureka Valley/Harvey Milk Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1961.0, yearRennovated: Optional(2009.0), sqFt: 6465.0, eui: 35.6),
    SFBuilding(pucCode: "245", facility: "Golden Gate Valley Branch Library", bldgCategory: "Libraries", facilityType: "library", yearBuilt: 1917.0, yearRennovated: Optional(2011.0), sqFt: 7432.0, eui: 33.3),
    SFBuilding(pucCode: "784", facility: "Multi-Service Center South", bldgCategory: "Health & Human Services", facilityType: "homeless service", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 25600.0, eui: 278.0),
    SFBuilding(pucCode: "785", facility: "Multi-Service Center North", bldgCategory: "Health & Human Services", facilityType: "homeless service", yearBuilt: 1913.0, yearRennovated: nil, sqFt: 37125.0, eui: 177.3),
    SFBuilding(pucCode: "1810", facility: "Mission Neighborhood Resource Center", bldgCategory: "Health & Human Services", facilityType: "homeless service", yearBuilt: 1922.0, yearRennovated: nil, sqFt: 6500.0, eui: 135.9),
    SFBuilding(pucCode: "57", facility: "Hamilton Family Shelter", bldgCategory: "Health & Human Services", facilityType: "homeless service", yearBuilt: 1966.0, yearRennovated: nil, sqFt: 50000.0, eui: 80.6),
    SFBuilding(pucCode: "184", facility: "Ocean Park Health Center (Health Center #5)", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1967.0, yearRennovated: Optional(2009.0), sqFt: 16247.0, eui: 169.9),
    SFBuilding(pucCode: "186", facility: "San Francisco City Clinic", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1930.0, yearRennovated: nil, sqFt: 8000.0, eui: 148.9),
    SFBuilding(pucCode: "175", facility: "Southeast Health Center", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1979.0, yearRennovated: Optional(2012.0), sqFt: 14604.0, eui: 140.4),
    SFBuilding(pucCode: "178", facility: "Castro Mission Health Center (Health Center #1)", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1965.0, yearRennovated: Optional(2008.0), sqFt: 15258.0, eui: 112.2),
    SFBuilding(pucCode: "179", facility: "Silver Avenue Health Center (Health Center #3)", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1967.0, yearRennovated: Optional(2005.0), sqFt: 22950.0, eui: 96.4),
    SFBuilding(pucCode: "180", facility: "Chinatown Public Health Center (Health Center #4)", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1967.0, yearRennovated: Optional(2010.0), sqFt: 22500.0, eui: 94.5),
    SFBuilding(pucCode: "185", facility: "Maxine Hall Health Center (Health Center #2)", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1966.0, yearRennovated: Optional(2006.0), sqFt: 20590.0, eui: 93.5),
    SFBuilding(pucCode: "181", facility: "Curry Senior Service Center", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1930.0, yearRennovated: Optional(2006.0), sqFt: 11195.0, eui: 88.7),
    SFBuilding(pucCode: "757", facility: "Potrero Hill Health Center", bldgCategory: "Health & Human Services", facilityType: "medical clinic", yearBuilt: 1976.0, yearRennovated: Optional(2012.0), sqFt: 8000.0, eui: 69.7),
    SFBuilding(pucCode: "183", facility: "Sunset Mental Health Services", bldgCategory: "Health & Human Services", facilityType: "mental health center", yearBuilt: 1949.0, yearRennovated: Optional(1972.0), sqFt: 5500.0, eui: 63.1),
    SFBuilding(pucCode: "200", facility: "S Van Ness Mental Health / Mission Family Center", bldgCategory: "Health & Human Services", facilityType: "mental health center", yearBuilt: 1958.0, yearRennovated: nil, sqFt: 14700.0, eui: 48.9),
    SFBuilding(pucCode: "1285", facility: "South of Market Mental Health Services", bldgCategory: "Health & Human Services", facilityType: "mental health center", yearBuilt: 1956.0, yearRennovated: Optional(1998.0), sqFt: 13000.0, eui: 47.9),
    SFBuilding(pucCode: "1809", facility: "SE Child/Family Therapy Center", bldgCategory: "Health & Human Services", facilityType: "mental health center", yearBuilt: 1939.0, yearRennovated: Optional(1998.0), sqFt: 3000.0, eui: 32.1),
    SFBuilding(pucCode: "1330", facility: "Chinatown Child Development Center", bldgCategory: "Health & Human Services", facilityType: "mental health center", yearBuilt: 1950.0, yearRennovated: Optional(1985.0), sqFt: 9250.0, eui: 30.0),
    SFBuilding(pucCode: "1456", facility: "Mission Mental Health Services", bldgCategory: "Health & Human Services", facilityType: "mental health center", yearBuilt: 1943.0, yearRennovated: Optional(2002.0), sqFt: 32000.0, eui: 23.0),
    SFBuilding(pucCode: "1956", facility: "Redwood Center", bldgCategory: "Health & Human Services", facilityType: "mental health center", yearBuilt: 1939.0, yearRennovated: nil, sqFt: 11000.0, eui: 10.6),
    SFBuilding(pucCode: "743", facility: "Animal Shelter", bldgCategory: "Health & Human Services", facilityType: "veterinarian", yearBuilt: 1931.0, yearRennovated: Optional(1989.0), sqFt: 29500.0, eui: 234.2),
    SFBuilding(pucCode: "192", facility: "San Francisco General Hospital", bldgCategory: "Hospitals", facilityType: "hospital", yearBuilt: 1915.0, yearRennovated: Optional(1976.0), sqFt: 1370904.0, eui: 376.6),
    SFBuilding(pucCode: "191", facility: "Laguna Honda Hospital", bldgCategory: "Hospitals", facilityType: "hospital", yearBuilt: 1926.0, yearRennovated: Optional(2010.0), sqFt: 717126.0, eui: 219.1),
    SFBuilding(pucCode: "1892", facility: "Temp Sewer Operations Office", bldgCategory: "Offices", facilityType: "office", yearBuilt: 2000.0, yearRennovated: nil, sqFt: 2500.0, eui: 149.8),
    SFBuilding(pucCode: "474", facility: "Hall of Justice", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1959.0, yearRennovated: nil, sqFt: 700000.0, eui: 126.2),
    SFBuilding(pucCode: "1402", facility: "SFUSD -- Administration - Franklin", bldgCategory: "Offices", facilityType: "Office", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 78028.0, eui: 125.2),
    SFBuilding(pucCode: "754", facility: "GGP -- McLaren Lodge and Annex", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1896.0, yearRennovated: Optional(1950.0), sqFt: 17252.0, eui: 101.7),
    SFBuilding(pucCode: "1324", facility: "Enforcement Division", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1920.0, yearRennovated: nil, sqFt: 8000.0, eui: 99.1),
    SFBuilding(pucCode: "1815", facility: "SFUSD -- 3045 Santiago Admin Building", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1954.0, yearRennovated: nil, sqFt: 15334.0, eui: 94.2),
    SFBuilding(pucCode: "174", facility: "DPH Central Office", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1932.0, yearRennovated: nil, sqFt: 119000.0, eui: 90.6),
    SFBuilding(pucCode: "793", facility: "CHN Headquarters", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1923.0, yearRennovated: Optional(1993.0), sqFt: 60000.0, eui: 85.3),
    SFBuilding(pucCode: "1124", facility: "SFUSD -- Academics and Professional Development", bldgCategory: "Offices", facilityType: "", yearBuilt: 1973.0, yearRennovated: nil, sqFt: 23400.0, eui: 82.2),
    SFBuilding(pucCode: "1404", facility: "Sheriff Training Facility", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1963.0, yearRennovated: Optional(2002.0), sqFt: 19057.0, eui: 75.7),
    SFBuilding(pucCode: "1150", facility: "1660 Mission St", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1990.0, yearRennovated: nil, sqFt: 90619.0, eui: 74.5),
    SFBuilding(pucCode: "1973", facility: "GGP -- Park Aid Station / Natural Areas Program", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1902.0, yearRennovated: Optional(2012.0), sqFt: 2733.0, eui: 74.1),
    SFBuilding(pucCode: "471", facility: "Women's Resource Center", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1959.0, yearRennovated: nil, sqFt: 5920.0, eui: 69.2),
    SFBuilding(pucCode: "779", facility: "1680 Mission St", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1923.0, yearRennovated: nil, sqFt: 41200.0, eui: 69.0),
    SFBuilding(pucCode: "808", facility: "30 Van Ness Ave", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1965.0, yearRennovated: nil, sqFt: 180939.0, eui: 67.8),
    SFBuilding(pucCode: "717", facility: "SFUSD -- Children's Center Administration Building", bldgCategory: "Offices", facilityType: "Office", yearBuilt: 1930.0, yearRennovated: nil, sqFt: 20000.0, eui: 66.6),
    SFBuilding(pucCode: "77", facility: "SFUSD -- Student Nutrition Services", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1932.0, yearRennovated: nil, sqFt: 9900.0, eui: 66.6),
    SFBuilding(pucCode: "91", facility: "Human Services Agency Headquarters", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1979.0, yearRennovated: nil, sqFt: 171385.0, eui: 64.0),
    SFBuilding(pucCode: "70", facility: "Investigations -- 160 South Van Ness", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1936.0, yearRennovated: Optional(2002.0), sqFt: 14219.0, eui: 63.7),
    SFBuilding(pucCode: "1378", facility: "SFFD - Headquarters", bldgCategory: "Offices", facilityType: "emergency center", yearBuilt: 1912.0, yearRennovated: Optional(1999.0), sqFt: 50000.0, eui: 61.4),
    SFBuilding(pucCode: "1703", facility: "SFUSD -- School Health Programs", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1950.0, yearRennovated: nil, sqFt: 13900.0, eui: 58.7),
    SFBuilding(pucCode: "832", facility: "Social Services -- 1235 Mission", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1935.0, yearRennovated: nil, sqFt: 124219.0, eui: 56.6),
    SFBuilding(pucCode: "1429", facility: "Library Support Services Building", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1925.0, yearRennovated: Optional(2001.0), sqFt: 43182.0, eui: 55.5),
    SFBuilding(pucCode: "1992", facility: "SFPUC -- 525 Golden Gate Ave", bldgCategory: "Offices", facilityType: "office", yearBuilt: 2012.0, yearRennovated: nil, sqFt: 277511.0, eui: 53.7),
    SFBuilding(pucCode: "1339", facility: "Former Gloria R Davis Middle", bldgCategory: "Offices", facilityType: "Office", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 60700.0, eui: 52.9),
    SFBuilding(pucCode: "813", facility: "25 Van Ness Ave", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1913.0, yearRennovated: Optional(1985.0), sqFt: 130000.0, eui: 51.0),
    SFBuilding(pucCode: "1886", facility: "One South Van Ness (OSVN)", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1959.0, yearRennovated: Optional(1989.0), sqFt: 655000.0, eui: 46.1),
    SFBuilding(pucCode: "425", facility: "CCSF -- Administrative Offices", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1949.0, yearRennovated: Optional(1971.0), sqFt: 50521.0, eui: 45.7),
    SFBuilding(pucCode: "472", facility: "City Hall", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1915.0, yearRennovated: Optional(2000.0), sqFt: 516484.0, eui: 44.2),
    SFBuilding(pucCode: "88", facility: "MediCal -- 1440 Harrison", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1921.0, yearRennovated: nil, sqFt: 52200.0, eui: 43.1),
    SFBuilding(pucCode: "1338", facility: "1155 Market St", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1983.0, yearRennovated: nil, sqFt: 158998.0, eui: 42.4),
    SFBuilding(pucCode: "1132", facility: "SFUSD -- Irving M Scott Building", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1895.0, yearRennovated: nil, sqFt: 12300.0, eui: 40.8),
    SFBuilding(pucCode: "1343", facility: "Seneca First Stop Visit Cntr/Workforce Development", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1947.0, yearRennovated: nil, sqFt: 8100.0, eui: 40.6),
    SFBuilding(pucCode: "1927", facility: "Airport Reprographics", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1967.0, yearRennovated: nil, sqFt: 6000.0, eui: 39.6),
    SFBuilding(pucCode: "715", facility: "Public Defender's Office", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1985.0, yearRennovated: nil, sqFt: 52000.0, eui: 32.3),
    SFBuilding(pucCode: "1066", facility: "SFUSD -- Administration - Van Ness", bldgCategory: "Offices", facilityType: "Office", yearBuilt: 1927.0, yearRennovated: nil, sqFt: 241956.0, eui: 22.7),
    SFBuilding(pucCode: "1998", facility: "Bayside Office Space and Warehouse", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1978.0, yearRennovated: nil, sqFt: 50593.0, eui: 11.0),
    SFBuilding(pucCode: "202", facility: "35/45 Onondaga Building", bldgCategory: "Offices", facilityType: "office", yearBuilt: 1928.0, yearRennovated: Optional(1932.0), sqFt: 8747.0, eui: 6.0),
    SFBuilding(pucCode: "1918", facility: "Community Justice Center", bldgCategory: "Offices", facilityType: "courthouse", yearBuilt: 1913.0, yearRennovated: nil, sqFt: 18430.0, eui: 59.7),
    SFBuilding(pucCode: "1379", facility: "Fire Station 35 (Fire Boat House)", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1908.0, yearRennovated: Optional(1994.0), sqFt: 4712.0, eui: 198.4),
    SFBuilding(pucCode: "41", facility: "Fire Station 34", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1929.0, yearRennovated: Optional(1998.0), sqFt: 4400.0, eui: 140.4),
    SFBuilding(pucCode: "30", facility: "Fire Station 22", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1962.0, yearRennovated: nil, sqFt: 5900.0, eui: 130.4),
    SFBuilding(pucCode: "28", facility: "Fire Station 20", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1963.0, yearRennovated: Optional(1997.0), sqFt: 10300.0, eui: 109.9),
    SFBuilding(pucCode: "51", facility: "Fire Station 43", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1970.0, yearRennovated: Optional(1995.0), sqFt: 10800.0, eui: 108.3),
    SFBuilding(pucCode: "35", facility: "Fire Station 29", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1956.0, yearRennovated: Optional(1996.0), sqFt: 8300.0, eui: 104.7),
    SFBuilding(pucCode: "38", facility: "Fire Station 31", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1913.0, yearRennovated: nil, sqFt: 8500.0, eui: 103.2),
    SFBuilding(pucCode: "23", facility: "Fire Station 16", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1938.0, yearRennovated: Optional(1998.0), sqFt: 14000.0, eui: 97.3),
    SFBuilding(pucCode: "26", facility: "Fire Station 19", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1951.0, yearRennovated: Optional(1998.0), sqFt: 11500.0, eui: 97.1),
    SFBuilding(pucCode: "18", facility: "Fire Station 11", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1956.0, yearRennovated: Optional(1996.0), sqFt: 14000.0, eui: 93.9),
    SFBuilding(pucCode: "24", facility: "Fire Station 05", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1954.0, yearRennovated: Optional(1984.0), sqFt: 12600.0, eui: 93.6),
    SFBuilding(pucCode: "22", facility: "Fire Station 15", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1957.0, yearRennovated: Optional(1997.0), sqFt: 12138.0, eui: 91.9),
    SFBuilding(pucCode: "53", facility: "Fire Station 06", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1948.0, yearRennovated: Optional(1998.0), sqFt: 13500.0, eui: 90.6),
    SFBuilding(pucCode: "29", facility: "Fire Station 21", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1958.0, yearRennovated: Optional(1988.0), sqFt: 8000.0, eui: 90.5),
    SFBuilding(pucCode: "20", facility: "Fire Station 13", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1974.0, yearRennovated: Optional(1999.0), sqFt: 18790.0, eui: 88.3),
    SFBuilding(pucCode: "17", facility: "Fire Station 10", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1956.0, yearRennovated: nil, sqFt: 14300.0, eui: 84.3),
    SFBuilding(pucCode: "52", facility: "Fire Station 17", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1955.0, yearRennovated: Optional(1996.0), sqFt: 12100.0, eui: 81.0),
    SFBuilding(pucCode: "56", facility: "Fire Station 07 / Division of Training", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1953.0, yearRennovated: Optional(2003.0), sqFt: 33600.0, eui: 73.5),
    SFBuilding(pucCode: "48", facility: "Fire Station 40", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1931.0, yearRennovated: Optional(1995.0), sqFt: 7350.0, eui: 73.3),
    SFBuilding(pucCode: "19", facility: "Fire Station 12", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1955.0, yearRennovated: nil, sqFt: 11300.0, eui: 71.8),
    SFBuilding(pucCode: "44", facility: "Fire Station 37", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1915.0, yearRennovated: Optional(1990.0), sqFt: 6950.0, eui: 68.0),
    SFBuilding(pucCode: "46", facility: "Fire Station 39", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1923.0, yearRennovated: Optional(1998.0), sqFt: 8450.0, eui: 66.7),
    SFBuilding(pucCode: "54", facility: "Fire Station 08", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1940.0, yearRennovated: Optional(1994.0), sqFt: 8000.0, eui: 63.1),
    SFBuilding(pucCode: "40", facility: "Fire Station 33", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1973.0, yearRennovated: Optional(1998.0), sqFt: 5900.0, eui: 62.6),
    SFBuilding(pucCode: "39", facility: "Fire Station 32", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1941.0, yearRennovated: Optional(1991.0), sqFt: 10900.0, eui: 62.3),
    SFBuilding(pucCode: "49", facility: "Fire Station 41", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1956.0, yearRennovated: nil, sqFt: 9600.0, eui: 59.3),
    SFBuilding(pucCode: "36", facility: "Fire Station 03", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1973.0, yearRennovated: nil, sqFt: 8000.0, eui: 53.2),
    SFBuilding(pucCode: "12", facility: "Fire Station 24", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1914.0, yearRennovated: Optional(1997.0), sqFt: 7600.0, eui: 51.7),
    SFBuilding(pucCode: "33", facility: "Fire Station 26", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1968.0, yearRennovated: Optional(1997.0), sqFt: 15000.0, eui: 51.2),
    SFBuilding(pucCode: "31", facility: "Fire Station 23", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1959.0, yearRennovated: Optional(1996.0), sqFt: 12000.0, eui: 50.9),
    SFBuilding(pucCode: "13", facility: "Fire Station 44", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1915.0, yearRennovated: Optional(1998.0), sqFt: 8450.0, eui: 50.3),
    SFBuilding(pucCode: "32", facility: "Fire Station 25", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1916.0, yearRennovated: nil, sqFt: 11420.0, eui: 50.3),
    SFBuilding(pucCode: "43", facility: "Fire Station 36", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1961.0, yearRennovated: Optional(1996.0), sqFt: 16100.0, eui: 44.7),
    SFBuilding(pucCode: "55", facility: "Fire Station 09", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1972.0, yearRennovated: Optional(1995.0), sqFt: 21400.0, eui: 42.4),
    SFBuilding(pucCode: "27", facility: "Fire Station 02", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1994.0, yearRennovated: nil, sqFt: 16920.0, eui: 42.0),
    SFBuilding(pucCode: "50", facility: "Fire Station 42", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1979.0, yearRennovated: Optional(1998.0), sqFt: 9300.0, eui: 41.4),
    SFBuilding(pucCode: "2019", facility: "Fire Station 01", bldgCategory: "Public Safety", facilityType: "fire stations", yearBuilt: 2013.0, yearRennovated: nil, sqFt: 15136.0, eui: 37.4),
    SFBuilding(pucCode: "21", facility: "Fire Station 14", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1973.0, yearRennovated: nil, sqFt: 15900.0, eui: 35.8),
    SFBuilding(pucCode: "25", facility: "Fire Station 18", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1951.0, yearRennovated: Optional(1997.0), sqFt: 15900.0, eui: 31.1),
    SFBuilding(pucCode: "42", facility: "Old Fire Station 01", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1953.0, yearRennovated: Optional(1992.0), sqFt: 14100.0, eui: 29.3),
    SFBuilding(pucCode: "1170", facility: "Fire Station 49", bldgCategory: "Public Safety", facilityType: "fire station", yearBuilt: 1958.0, yearRennovated: Optional(2002.0), sqFt: 75000.0, eui: 12.7),
    SFBuilding(pucCode: "73", facility: "Central Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1970.0, yearRennovated: nil, sqFt: 8000.0, eui: 130.5),
    SFBuilding(pucCode: "74", facility: "Ingleside Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1910.0, yearRennovated: Optional(1990.0), sqFt: 18500.0, eui: 122.7),
    SFBuilding(pucCode: "78", facility: "Park Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1910.0, yearRennovated: Optional(1993.0), sqFt: 13700.0, eui: 112.2),
    SFBuilding(pucCode: "1213", facility: "Bayview Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1996.0, yearRennovated: nil, sqFt: 16000.0, eui: 90.7),
    SFBuilding(pucCode: "1924", facility: "SFPD Tactical Company", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1941.0, yearRennovated: Optional(2009.0), sqFt: 52125.0, eui: 79.4),
    SFBuilding(pucCode: "811", facility: "Mission Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1994.0, yearRennovated: nil, sqFt: 25000.0, eui: 76.8),
    SFBuilding(pucCode: "712", facility: "Northern Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1988.0, yearRennovated: Optional(1987.0), sqFt: 18000.0, eui: 74.3),
    SFBuilding(pucCode: "87", facility: "Taraval Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1929.0, yearRennovated: Optional(1994.0), sqFt: 18070.0, eui: 71.1),
    SFBuilding(pucCode: "84", facility: "Richmond Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 1910.0, yearRennovated: Optional(1993.0), sqFt: 13000.0, eui: 60.5),
    SFBuilding(pucCode: "791", facility: "Tenderloin Police Station", bldgCategory: "Public Safety", facilityType: "police station", yearBuilt: 2000.0, yearRennovated: nil, sqFt: 27500.0, eui: 44.8),
    SFBuilding(pucCode: "1336", facility: "Emergency Operations Center", bldgCategory: "Public Safety", facilityType: "emergency center", yearBuilt: 1998.0, yearRennovated: Optional(2010.0), sqFt: 56000.0, eui: 210.1),
    SFBuilding(pucCode: "92", facility: "San Francisco County Jail, San Bruno Facility", bldgCategory: "Public Safety", facilityType: "jail / correctional", yearBuilt: 1934.0, yearRennovated: Optional(2006.0), sqFt: 348202.0, eui: 133.6),
    SFBuilding(pucCode: "94", facility: "Youth Guidance Center", bldgCategory: "Public Safety", facilityType: "jail / correctional", yearBuilt: 1950.0, yearRennovated: Optional(2006.0), sqFt: 210000.0, eui: 128.0),
    SFBuilding(pucCode: "1205", facility: "County Jail #1 & #2", bldgCategory: "Public Safety", facilityType: "jail / correctional", yearBuilt: 1994.0, yearRennovated: nil, sqFt: 250000.0, eui: 41.4),
    SFBuilding(pucCode: "388", facility: "South Sunset Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1949.0, yearRennovated: nil, sqFt: 1500.0, eui: 232.3),
    SFBuilding(pucCode: "1704", facility: "Sandy Tatum Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2005.0, yearRennovated: nil, sqFt: 20000.0, eui: 195.4),
    SFBuilding(pucCode: "408", facility: "Youngblood Coleman Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1960.0, yearRennovated: nil, sqFt: 2135.0, eui: 147.8),
    SFBuilding(pucCode: "337", facility: "Laurel Hill Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1953.0, yearRennovated: nil, sqFt: 1134.0, eui: 147.1),
    SFBuilding(pucCode: "327", facility: "James Rolph Jr Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1921.0, yearRennovated: Optional(2008.0), sqFt: 2730.0, eui: 120.5),
    SFBuilding(pucCode: "401", facility: "Visitacion Valley Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2003.0, yearRennovated: nil, sqFt: 2600.0, eui: 98.7),
    SFBuilding(pucCode: "346", facility: "Merced Heights Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1950.0, yearRennovated: nil, sqFt: 1136.0, eui: 96.9),
    SFBuilding(pucCode: "1141", facility: "GGP -- Golf Course Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1951.0, yearRennovated: nil, sqFt: 2470.0, eui: 92.3),
    SFBuilding(pucCode: "567", facility: "Helen Wills Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2005.0, yearRennovated: nil, sqFt: 3082.0, eui: 91.5),
    SFBuilding(pucCode: "411", facility: "Lincoln Park Golf Course", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1936.0, yearRennovated: nil, sqFt: 6329.0, eui: 85.8),
    SFBuilding(pucCode: "306", facility: "Jose Coronado Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1995.0, yearRennovated: nil, sqFt: 933.0, eui: 79.4),
    SFBuilding(pucCode: "394", facility: "GGP -- Stow Lake Boathouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1945.0, yearRennovated: nil, sqFt: 4647.0, eui: 78.4),
    SFBuilding(pucCode: "275", facility: "Argonne Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2006.0, yearRennovated: nil, sqFt: 1000.0, eui: 75.5),
    SFBuilding(pucCode: "316", facility: "Hayes Valley Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2011.0, yearRennovated: nil, sqFt: 2500.0, eui: 71.8),
    SFBuilding(pucCode: "307", facility: "Fulton Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1955.0, yearRennovated: Optional(2012.0), sqFt: 1420.0, eui: 71.7),
    SFBuilding(pucCode: "386", facility: "Silver Terrace Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1953.0, yearRennovated: nil, sqFt: 7842.0, eui: 61.4),
    SFBuilding(pucCode: "344", facility: "Mccoppin Square Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1955.0, yearRennovated: nil, sqFt: 2000.0, eui: 54.7),
    SFBuilding(pucCode: "325", facility: "Jackson Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1912.0, yearRennovated: nil, sqFt: 8060.0, eui: 51.4),
    SFBuilding(pucCode: "347", facility: "Midtown Terrace Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1961.0, yearRennovated: nil, sqFt: 2176.0, eui: 50.4),
    SFBuilding(pucCode: "1446", facility: "Parque Ninos Unidos Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2004.0, yearRennovated: nil, sqFt: 2414.0, eui: 50.1),
    SFBuilding(pucCode: "561", facility: "Gilman Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1969.0, yearRennovated: nil, sqFt: 1578.0, eui: 50.0),
    SFBuilding(pucCode: "341", facility: "Margaret S Hayward Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1922.0, yearRennovated: nil, sqFt: 6717.0, eui: 48.0),
    SFBuilding(pucCode: "289", facility: "Christopher Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1971.0, yearRennovated: nil, sqFt: 2337.0, eui: 41.2),
    SFBuilding(pucCode: "372", facility: "Wawona Clubhouse (Project Insight)", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1950.0, yearRennovated: nil, sqFt: 1830.0, eui: 39.3),
    SFBuilding(pucCode: "284", facility: "Cayuga Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2013.0, yearRennovated: nil, sqFt: 2500.0, eui: 38.6),
    SFBuilding(pucCode: "371", facility: "Peixotto Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1955.0, yearRennovated: nil, sqFt: 2000.0, eui: 30.0),
    SFBuilding(pucCode: "304", facility: "Excelsior Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1928.0, yearRennovated: nil, sqFt: 2255.0, eui: 28.7),
    SFBuilding(pucCode: "730", facility: "Sunnyside Conservatory", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1900.0, yearRennovated: Optional(2009.0), sqFt: 1536.0, eui: 27.0),
    SFBuilding(pucCode: "380", facility: "Richmond Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1916.0, yearRennovated: nil, sqFt: 1200.0, eui: 26.2),
    SFBuilding(pucCode: "397", facility: "Sunnyside Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1969.0, yearRennovated: nil, sqFt: 4412.0, eui: 25.5),
    SFBuilding(pucCode: "348", facility: "Cow Hollow Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1950.0, yearRennovated: nil, sqFt: 675.0, eui: 23.4),
    SFBuilding(pucCode: "362", facility: "J. P. Murphy Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1950.0, yearRennovated: Optional(2008.0), sqFt: 1820.0, eui: 23.0),
    SFBuilding(pucCode: "385", facility: "Sigmund Stern Grove / Trocadero Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1930.0, yearRennovated: Optional(2005.0), sqFt: 12832.0, eui: 22.6),
    SFBuilding(pucCode: "381", facility: "Rochambeau Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2004.0, yearRennovated: nil, sqFt: 1482.0, eui: 22.1),
    SFBuilding(pucCode: "301", facility: "Douglas Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1926.0, yearRennovated: nil, sqFt: 1072.0, eui: 22.1),
    SFBuilding(pucCode: "312", facility: "Grattan Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1949.0, yearRennovated: nil, sqFt: 1854.0, eui: 20.6),
    SFBuilding(pucCode: "402", facility: "West Portal Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 2004.0, yearRennovated: nil, sqFt: 2728.0, eui: 20.2),
    SFBuilding(pucCode: "324", facility: "Julius Kahn Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1922.0, yearRennovated: nil, sqFt: 1105.0, eui: 20.1),
    SFBuilding(pucCode: "1311", facility: "Woh Hei Yuen Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1997.0, yearRennovated: nil, sqFt: 5000.0, eui: 19.3),
    SFBuilding(pucCode: "355", facility: "Miraloma Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1949.0, yearRennovated: nil, sqFt: 1352.0, eui: 17.4),
    SFBuilding(pucCode: "283", facility: "Cabrillo Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1931.0, yearRennovated: Optional(2013.0), sqFt: 1420.0, eui: 17.1),
    SFBuilding(pucCode: "731", facility: "Boeddeker Park and Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1989.0, yearRennovated: nil, sqFt: 3740.0, eui: 14.7),
    SFBuilding(pucCode: "329", facility: "Junipero Serra Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1955.0, yearRennovated: Optional(2008.0), sqFt: 1700.0, eui: 14.7),
    SFBuilding(pucCode: "777", facility: "Alice Chalmers Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1951.0, yearRennovated: nil, sqFt: 2505.0, eui: 11.7),
    SFBuilding(pucCode: "377", facility: "Presidio Heights Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1910.0, yearRennovated: nil, sqFt: 958.0, eui: 11.7),
    SFBuilding(pucCode: "287", facility: "Willie Woo Woo Wong Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1927.0, yearRennovated: nil, sqFt: 6000.0, eui: 11.5),
    SFBuilding(pucCode: "405", facility: "West Sunset Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1953.0, yearRennovated: nil, sqFt: 13530.0, eui: 9.7),
    SFBuilding(pucCode: "335", facility: "Lake Merced Boathouse", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1958.0, yearRennovated: Optional(2013.0), sqFt: 15200.0, eui: 7.9),
    SFBuilding(pucCode: "1699", facility: "Pine Lake Park Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1950.0, yearRennovated: nil, sqFt: 1242.0, eui: 7.4),
    SFBuilding(pucCode: "299", facility: "Crocker Amazon Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "clubhouse", yearBuilt: 1955.0, yearRennovated: Optional(1982.0), sqFt: 24040.0, eui: 7.1),
    SFBuilding(pucCode: "308", facility: "Moscone Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1924.0, yearRennovated: Optional(2008.0), sqFt: 9650.0, eui: 131.5),
    SFBuilding(pucCode: "303", facility: "Eureka Valley Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1951.0, yearRennovated: Optional(2004.0), sqFt: 17880.0, eui: 106.9),
    SFBuilding(pucCode: "328", facility: "Joseph Lee Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1950.0, yearRennovated: Optional(2007.0), sqFt: 16383.0, eui: 91.4),
    SFBuilding(pucCode: "375", facility: "Potrero Hill Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1950.0, yearRennovated: nil, sqFt: 18805.0, eui: 77.5),
    SFBuilding(pucCode: "366", facility: "Minnie & Lovie Ward Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 2007.0, yearRennovated: Optional(2008.0), sqFt: 19461.0, eui: 70.2),
    SFBuilding(pucCode: "1439", facility: "Richmond Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 2000.0, yearRennovated: nil, sqFt: 18470.0, eui: 67.2),
    SFBuilding(pucCode: "392", facility: "St. Mary's Rec Center and Playground", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1949.0, yearRennovated: nil, sqFt: 23307.0, eui: 59.6),
    SFBuilding(pucCode: "314", facility: "GGP -- County Fair Building/Hall Of Flowers", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1961.0, yearRennovated: Optional(1969.0), sqFt: 23477.0, eui: 58.8),
    SFBuilding(pucCode: "400", facility: "Upper Noe Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1950.0, yearRennovated: Optional(2006.0), sqFt: 16447.0, eui: 58.5),
    SFBuilding(pucCode: "1172", facility: "Tenderloin Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1995.0, yearRennovated: nil, sqFt: 10133.0, eui: 48.6),
    SFBuilding(pucCode: "398", facility: "Sunset Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1940.0, yearRennovated: Optional(2012.0), sqFt: 16424.0, eui: 48.0),
    SFBuilding(pucCode: "279", facility: "Bernal Heights Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1932.0, yearRennovated: nil, sqFt: 5008.0, eui: 42.0),
    SFBuilding(pucCode: "356", facility: "Mission Rec Center / Mission Arts Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1984.0, yearRennovated: Optional(2012.0), sqFt: 30850.0, eui: 40.3),
    SFBuilding(pucCode: "288", facility: "Betty Ann Ong Chinese Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1951.0, yearRennovated: Optional(2012.0), sqFt: 24234.0, eui: 34.5),
    SFBuilding(pucCode: "359", facility: "GGP -- Model Yacht Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1938.0, yearRennovated: nil, sqFt: 3168.0, eui: 32.4),
    SFBuilding(pucCode: "755", facility: "Gene Friend Rec Center @ SOMA", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1989.0, yearRennovated: nil, sqFt: 16354.0, eui: 19.6),
    SFBuilding(pucCode: "1139", facility: "GGP -- Kezar Pavilion", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1925.0, yearRennovated: nil, sqFt: 24254.0, eui: 16.8),
    SFBuilding(pucCode: "387", facility: "Glen Park Rec Center / Glenridge Nursery School", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1934.0, yearRennovated: nil, sqFt: 22301.0, eui: 14.0),
    SFBuilding(pucCode: "373", facility: "Palega Rec Center", bldgCategory: "Recreation Facilities", facilityType: "recreation center", yearBuilt: 1928.0, yearRennovated: Optional(2012.0), sqFt: 18397.0, eui: 7.5),
    SFBuilding(pucCode: "382", facility: "Rossi Swimming Pool and Playground", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 1958.0, yearRennovated: nil, sqFt: 15162.0, eui: 433.3),
    SFBuilding(pucCode: "336", facility: "Charlie Sava Swimming Pool / Larsen Park", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 1957.0, yearRennovated: Optional(2008.0), sqFt: 12900.0, eui: 433.1),
    SFBuilding(pucCode: "701", facility: "Coffman Pool / Herz Clubhouse and Playground", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 1957.0, yearRennovated: Optional(2008.0), sqFt: 12289.0, eui: 378.2),
    SFBuilding(pucCode: "310", facility: "Garfield Pool and Garfield Square Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 1958.0, yearRennovated: nil, sqFt: 21160.0, eui: 247.0),
    SFBuilding(pucCode: "365", facility: "North Beach Swimming Pool/Joe DiMaggio Playground", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 2004.0, yearRennovated: Optional(2006.0), sqFt: 16384.0, eui: 240.5),
    SFBuilding(pucCode: "343", facility: "Martin Luther King Jr Swimming Pool", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 2001.0, yearRennovated: nil, sqFt: 23851.0, eui: 222.4),
    SFBuilding(pucCode: "358", facility: "Mission Community Pool / Clubhouse", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 1916.0, yearRennovated: Optional(2012.0), sqFt: 8500.0, eui: 143.6),
    SFBuilding(pucCode: "315", facility: "Hamilton Rec Center and Pool", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 1953.0, yearRennovated: Optional(2010.0), sqFt: 16988.0, eui: 122.4),
    SFBuilding(pucCode: "703", facility: "Balboa Swimming Pool", bldgCategory: "Recreation Facilities", facilityType: "pool", yearBuilt: 1962.0, yearRennovated: nil, sqFt: 19000.0, eui: 32.4),
    SFBuilding(pucCode: "391", facility: "GGP -- Murphy Millwright's Cottage", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1904.0, yearRennovated: Optional(2011.0), sqFt: 2960.0, eui: 617.9),
    SFBuilding(pucCode: "409", facility: "SF Zoo", bldgCategory: "Recreation Facilities", facilityType: "zoo", yearBuilt: 1930.0, yearRennovated: nil, sqFt: 65799.0, eui: 356.4),
    SFBuilding(pucCode: "331", facility: "GGP -- Kezar Stadium", bldgCategory: "Recreation Facilities", facilityType: "stadium", yearBuilt: 1924.0, yearRennovated: nil, sqFt: 5000.0, eui: 280.1),
    SFBuilding(pucCode: "1299", facility: "GGP -- Beach Chalet and Visitor Center", bldgCategory: "Recreation Facilities", facilityType: "restaurant", yearBuilt: 1925.0, yearRennovated: Optional(1996.0), sqFt: 18045.0, eui: 236.4),
    SFBuilding(pucCode: "363", facility: "GGP -- Music Concourse", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1900.0, yearRennovated: nil, sqFt: 5095.0, eui: 125.7),
    SFBuilding(pucCode: "81", facility: "SFPD Stables", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1935.0, yearRennovated: nil, sqFt: 11800.0, eui: 72.8),
    SFBuilding(pucCode: "272", facility: "GGP -- Dutch Windmill", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1902.0, yearRennovated: nil, sqFt: 2500.0, eui: 54.8),
    SFBuilding(pucCode: "79", facility: "SFPD Pistol Range", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1942.0, yearRennovated: Optional(1989.0), sqFt: 10000.0, eui: 53.9),
    SFBuilding(pucCode: "410", facility: "Candlestick Park Stadium", bldgCategory: "Recreation Facilities", facilityType: "stadium", yearBuilt: 1960.0, yearRennovated: nil, sqFt: 500000.0, eui: 41.3),
    SFBuilding(pucCode: "1326", facility: "GGP -- Pioneer Log Cabin", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1911.0, yearRennovated: Optional(1931.0), sqFt: 2256.0, eui: 36.1),
    SFBuilding(pucCode: "278", facility: "GGP -- Bercut Equitation Field", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1930.0, yearRennovated: nil, sqFt: 20632.0, eui: 11.3),
    SFBuilding(pucCode: "1383", facility: "Fay House", bldgCategory: "Recreation Facilities", facilityType: "park building", yearBuilt: 1912.0, yearRennovated: nil, sqFt: 4536.0, eui: 1.2),
    SFBuilding(pucCode: "298", facility: "GGP -- Maintenance Yard and Nursery", bldgCategory: "Service, Repair, and Storage", facilityType: "corporation yard", yearBuilt: 1957.0, yearRennovated: nil, sqFt: 43947.0, eui: 223.2),
    SFBuilding(pucCode: "505", facility: "Kirkland Division - Motor Coach", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1949.0, yearRennovated: nil, sqFt: 9352.0, eui: 166.1),
    SFBuilding(pucCode: "506", facility: "Cable Car Barn and Power House", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1906.0, yearRennovated: Optional(1984.0), sqFt: 83741.0, eui: 160.8),
    SFBuilding(pucCode: "1900", facility: "Metro East Facility - LRV", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 2008.0, yearRennovated: nil, sqFt: 180000.0, eui: 144.1),
    SFBuilding(pucCode: "530", facility: "Cameron Beach (Geneva) Yard - LRV and Streetcar", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1984.0, yearRennovated: nil, sqFt: 31514.0, eui: 117.1),
    SFBuilding(pucCode: "516", facility: "Woods Division - Motor Coach", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1976.0, yearRennovated: nil, sqFt: 161719.0, eui: 100.3),
    SFBuilding(pucCode: "1702", facility: "Green Division and Annex - LRV", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1977.0, yearRennovated: Optional(1983.0), sqFt: 208371.0, eui: 66.7),
    SFBuilding(pucCode: "778", facility: "Islais Creek - Motor Coach", bldgCategory: "Service, Repair, and Storage", facilityType: "corporation yard", yearBuilt: 2013.0, yearRennovated: nil, sqFt: 16200.0, eui: 66.5),
    SFBuilding(pucCode: "553", facility: "Potrero Division - Trolley Coach", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1914.0, yearRennovated: Optional(1990.0), sqFt: 101510.0, eui: 63.9),
    SFBuilding(pucCode: "523", facility: "Flynn Division - Motor Coach", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1941.0, yearRennovated: Optional(1989.0), sqFt: 268947.0, eui: 57.5),
    SFBuilding(pucCode: "98", facility: "Old DT Corporation Yard", bldgCategory: "Service, Repair, and Storage", facilityType: "corporation yard", yearBuilt: 1950.0, yearRennovated: nil, sqFt: 45000.0, eui: 54.7),
    SFBuilding(pucCode: "107", facility: "Hall of Justice Gas Station", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1959.0, yearRennovated: nil, sqFt: 4360.0, eui: 54.2),
    SFBuilding(pucCode: "1393", facility: "1399 Marin - Maintenance Facility", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 25100.0, eui: 51.7),
    SFBuilding(pucCode: "515", facility: "Presidio Division - Trolley Coach", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1912.0, yearRennovated: nil, sqFt: 158381.0, eui: 49.2),
    SFBuilding(pucCode: "1468", facility: "Central Shops", bldgCategory: "Service, Repair, and Storage", facilityType: "corporation yard", yearBuilt: 1959.0, yearRennovated: nil, sqFt: 80577.0, eui: 48.6),
    SFBuilding(pucCode: "111", facility: "DPW -- Corporation Yard", bldgCategory: "Service, Repair, and Storage", facilityType: "corporation yard", yearBuilt: 1949.0, yearRennovated: nil, sqFt: 102764.0, eui: 40.8),
    SFBuilding(pucCode: "396", facility: "GGP -- San Francisco Botanical Garden", bldgCategory: "Service, Repair, and Storage", facilityType: "corporation yard", yearBuilt: 1955.0, yearRennovated: nil, sqFt: 29763.0, eui: 35.6),
    SFBuilding(pucCode: "744", facility: "Scott Division", bldgCategory: "Service, Repair, and Storage", facilityType: "gas station/vehicle repair", yearBuilt: 1990.0, yearRennovated: nil, sqFt: 116144.0, eui: 16.7),
    SFBuilding(pucCode: "8", facility: "SFFD - Bureau of Equipment", bldgCategory: "Service, Repair, and Storage", facilityType: "shop", yearBuilt: 1918.0, yearRennovated: nil, sqFt: 7000.0, eui: 65.3),
    SFBuilding(pucCode: "2012", facility: "ReproMail", bldgCategory: "Service, Repair, and Storage", facilityType: "shop", yearBuilt: 1935.0, yearRennovated: nil, sqFt: 10469.0, eui: 55.8),
    SFBuilding(pucCode: "1032", facility: "SFUSD -- Buildings and Grounds", bldgCategory: "Service, Repair, and Storage", facilityType: "Shop", yearBuilt: 1968.0, yearRennovated: nil, sqFt: 40000.0, eui: 50.5),
    SFBuilding(pucCode: "1290", facility: "700 Pennsylvania - Maintenance of Way", bldgCategory: "Service, Repair, and Storage", facilityType: "shop", yearBuilt: 1947.0, yearRennovated: Optional(2000.0), sqFt: 99383.0, eui: 35.5),
    SFBuilding(pucCode: "1964", facility: "Sustainable Streets Division", bldgCategory: "Service, Repair, and Storage", facilityType: "shop", yearBuilt: 1999.0, yearRennovated: nil, sqFt: 90000.0, eui: 17.1),
    SFBuilding(pucCode: "1292", facility: "1401 Bryant - Overhead Lines", bldgCategory: "Service, Repair, and Storage", facilityType: "shop", yearBuilt: 1897.0, yearRennovated: Optional(1979.0), sqFt: 46000.0, eui: 13.6),
    SFBuilding(pucCode: "124", facility: "Paint Shop and Vehicle Parking", bldgCategory: "Service, Repair, and Storage", facilityType: "shop", yearBuilt: 1958.0, yearRennovated: nil, sqFt: 35021.0, eui: 4.2),
    SFBuilding(pucCode: "1031", facility: "SFUSD -- Warehouse/Transportation", bldgCategory: "Service, Repair, and Storage", facilityType: "Warehouse", yearBuilt: 1946.0, yearRennovated: nil, sqFt: 132000.0, eui: 22.4),
    SFBuilding(pucCode: "1929", facility: "651 Bryant - Power Utility Services", bldgCategory: "Service, Repair, and Storage", facilityType: "warehouse", yearBuilt: 1954.0, yearRennovated: nil, sqFt: 14000.0, eui: 19.6),
    SFBuilding(pucCode: "756", facility: "Streetlight Warehouse", bldgCategory: "Service, Repair, and Storage", facilityType: "warehouse", yearBuilt: 1988.0, yearRennovated: nil, sqFt: 6400.0, eui: 14.4),
    SFBuilding(pucCode: "103", facility: "Brooks Hall", bldgCategory: "Service, Repair, and Storage", facilityType: "warehouse", yearBuilt: 1956.0, yearRennovated: nil, sqFt: 90000.0, eui: 13.3),
    SFBuilding(pucCode: "1873", facility: "Burke Avenue Facility - Central Warehouse", bldgCategory: "Service, Repair, and Storage", facilityType: "warehouse", yearBuilt: 1969.0, yearRennovated: nil, sqFt: 103231.0, eui: 12.5),
    SFBuilding(pucCode: "1222", facility: "Fine Arts Warehouse", bldgCategory: "Service, Repair, and Storage", facilityType: "warehouse", yearBuilt: 1983.0, yearRennovated: nil, sqFt: 27440.0, eui: 6.2),
    SFBuilding(pucCode: "207", facility: "Civic Center Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1958.0, yearRennovated: nil, sqFt: 355674.0, eui: 13.0),
    SFBuilding(pucCode: "1476", facility: "Union Square Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1941.0, yearRennovated: nil, sqFt: 423780.0, eui: 11.9),
    SFBuilding(pucCode: "232", facility: "Portsmouth Square Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1962.0, yearRennovated: nil, sqFt: 225480.0, eui: 9.6),
    SFBuilding(pucCode: "234", facility: "Vallejo Street Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1969.0, yearRennovated: nil, sqFt: 62760.0, eui: 9.6),
    SFBuilding(pucCode: "706", facility: "Sixteenth & Hoff Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1996.0, yearRennovated: nil, sqFt: 17284.0, eui: 9.2),
    SFBuilding(pucCode: "1796", facility: "Music Concourse Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 2005.0, yearRennovated: nil, sqFt: 300000.0, eui: 8.4),
    SFBuilding(pucCode: "211", facility: "Golden Gateway Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1965.0, yearRennovated: nil, sqFt: 226800.0, eui: 8.3),
    SFBuilding(pucCode: "1214", facility: "SF General Hospital Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1996.0, yearRennovated: nil, sqFt: 300000.0, eui: 8.1),
    SFBuilding(pucCode: "1235", facility: "Polk Bush Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1993.0, yearRennovated: nil, sqFt: 70160.0, eui: 7.8),
    SFBuilding(pucCode: "233", facility: "Sutter Stockton Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1959.0, yearRennovated: nil, sqFt: 717970.0, eui: 7.6),
    SFBuilding(pucCode: "222", facility: "Fifth & Mission Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1957.0, yearRennovated: nil, sqFt: 992600.0, eui: 7.3),
    SFBuilding(pucCode: "215", facility: "Moscone Center Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1984.0, yearRennovated: nil, sqFt: 255444.0, eui: 7.2),
    SFBuilding(pucCode: "716", facility: "St Mary's Square Parking Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1952.0, yearRennovated: nil, sqFt: 245445.0, eui: 7.0),
    SFBuilding(pucCode: "208", facility: "Ellis O'Farrell Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1964.0, yearRennovated: nil, sqFt: 304520.0, eui: 7.0),
    SFBuilding(pucCode: "216", facility: "Mission Bartlett Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1983.0, yearRennovated: nil, sqFt: 113759.0, eui: 6.6),
    SFBuilding(pucCode: "231", facility: "Performing Arts Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1983.0, yearRennovated: nil, sqFt: 209896.0, eui: 6.3),
    SFBuilding(pucCode: "1219", facility: "Japan Center Garage - Fillmore Street Annex", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1965.0, yearRennovated: nil, sqFt: 59308.0, eui: 6.2),
    SFBuilding(pucCode: "1921", facility: "North Beach Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 2002.0, yearRennovated: nil, sqFt: 82405.0, eui: 5.5),
    SFBuilding(pucCode: "2039", facility: "SFUSD -- 1340 Bush Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1969.0, yearRennovated: nil, sqFt: 13316.0, eui: 5.1),
    SFBuilding(pucCode: "710", facility: "Lombard Street Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1988.0, yearRennovated: nil, sqFt: 71263.0, eui: 5.0),
    SFBuilding(pucCode: "213", facility: "Japan Center Main Garage", bldgCategory: "Parking Garages", facilityType: "parking garage", yearBuilt: 1965.0, yearRennovated: nil, sqFt: 237566.0, eui: 4.9),
    SFBuilding(pucCode: "509", facility: "Castro Station", bldgCategory: "Transit Stations", facilityType: "muni station", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 31000.0, eui: 77.3),
    SFBuilding(pucCode: "1221", facility: "Forest Hill Station", bldgCategory: "Transit Stations", facilityType: "muni station", yearBuilt: 1918.0, yearRennovated: Optional(1986.0), sqFt: 26000.0, eui: 69.8),
    SFBuilding(pucCode: "513", facility: "Embarcadero Station", bldgCategory: "Transit Stations", facilityType: "muni station", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 56000.0, eui: 66.3),
    SFBuilding(pucCode: "510", facility: "Church Station", bldgCategory: "Transit Stations", facilityType: "muni station", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 39000.0, eui: 56.1),
    SFBuilding(pucCode: "554", facility: "Powell Station", bldgCategory: "Transit Stations", facilityType: "muni station", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 59000.0, eui: 53.6),
    SFBuilding(pucCode: "511", facility: "Civic Center Station", bldgCategory: "Transit Stations", facilityType: "muni station", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 53000.0, eui: 52.1),
    SFBuilding(pucCode: "549", facility: "Van Ness Station", bldgCategory: "Transit Stations", facilityType: "muni station", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 42000.0, eui: 51.1),
    SFBuilding(pucCode: "504", facility: "Montgomery Station", bldgCategory: "Transit Stations", facilityType: "muni station", yearBuilt: 1972.0, yearRennovated: nil, sqFt: 57000.0, eui: 49.2),
    SFBuilding(pucCode: "485", facility: "San Francisco International Airport", bldgCategory: "Airport", facilityType: "airport", yearBuilt: 1954.0, yearRennovated: nil, sqFt: 42000.0, eui: 97.4),
]

/*
 - 0 : "Airport"
 - 1 : "Convention Centers"
 - 2 : "Education"
 - 3 : "Health & Human Services"
 - 4 : "Hospitals"
 - 5 : "Libraries"
 - 6 : "Museums and Art"
 - 7 : "Offices"
 - 8 : "Parking Garages"
 - 9 : "Performance Halls"
 - 10 : "Public Safety"
 - 11 : "Recreation Facilities"
 - 12 : "Service, Repair, and Storage"
 - 13 : "Transit Stations"
 */
let SFBuildingFacilityTypes = Array(Set(SFBuildings.map { $0.bldgCategory })).sorted()

var SFBuildingFacilities: [String: [SFBuilding]]  {
    var facilities: [String: [SFBuilding]] = [:]
    
    for facilityType in SFBuildingFacilityTypes {
        facilities[facilityType] = SFBuildings.filter { $0.bldgCategory == facilityType }
    }
    
    return facilities
}
