import Foundation
import SwiftUI

/**
 Components in this file will have `View` and `Style` definitions generated by Sourcery.
 */

// sourcery: isBaseComponent
protocol _TitleComponent {
    // sourcery: isViewBuilder
    var title: AttributedString { get }
}

// sourcery: isBaseComponent
protocol _SubtitleComponent {
    // sourcery: isViewBuilder
    var subtitle: AttributedString? { get }
}

// sourcery: isBaseComponent
protocol _TagsComponent {
    // sourcery: resultBuilder.name = @TagBuilder, resultBuilder.backingComponent = TagStack
    var tags: [AttributedString] { get }
}

// sourcery: isBaseComponent
protocol _ActionTitleComponent {
    // sourcery: isViewBuilder
    var actionTitle: AttributedString? { get }
}

// sourcery: isBaseComponent
protocol _FootnoteComponent {
    // sourcery: isViewBuilder
    var footnote: AttributedString? { get }
}

// sourcery: isBaseComponent
protocol _DescriptionComponent {
    // sourcery: isViewBuilder
    var description: AttributedString? { get }
}

// sourcery: isBaseComponent
protocol _StatusComponent {
    // sourcery: resultBuilder.name = @ViewBuilder, resultBuilder.backingComponent = TextOrIconView
    var status: TextOrIcon? { get }
}

// sourcery: isBaseComponent
protocol _SubstatusComponent {
    // sourcery: resultBuilder.name = @ViewBuilder, resultBuilder.backingComponent = TextOrIconView
    var substatus: TextOrIcon? { get }
}

// sourcery: isBaseComponent
protocol _DetailImageComponent {
    // sourcery: isViewBuilder
    var detailImage: Image? { get }
}

// sourcery: isBaseComponent
protocol _IconsComponent {
    // sourcery: resultBuilder.name = @IconBuilder, resultBuilder.backingComponent = IconStack
    var icons: [TextOrIcon] { get }
}

// sourcery: isBaseComponent
protocol _FootnoteIconsComponent {
    // sourcery: resultBuilder.name = @FootnoteIconsBuilder, resultBuilder.backingComponent = FootnoteIconStack
    var footnoteIcons: [TextOrIcon] { get }
}

// sourcery: isBaseComponent
protocol _AvatarsComponent {
    // sourcery: resultBuilder.name = @AvatarsBuilder, resultBuilder.backingComponent = AvatarStack
    var avatars: [TextOrIcon] { get }
}

// protocol _SwitchComponent {
//    // sourcery: isBinding
//    var isOn: Bool { get }
// }
