import FioriSwiftUICore
import SwiftUI

struct BannerMessageModifierExample: View {
    @State var show: Bool = true
    @State var pushContentDown: Bool = false
    @State var withLink: Bool = false
    @State var withAttachedAction: Bool = false
    @State var withLongText: Bool = false
    @State var showBottomSheet: Bool = false
    @State var messageType: BannerMultiMessageType = .negative
    @State var hidesCloseAction: Bool = false
    @State var alignment: Int = 1
    
    @ViewBuilder
    var titleView: some View {
        let text = self.withLongText ? "This is a very very very very very very very very very very very long banner message. " : "This is a banner message. "
        let noticeText = self.withLongText ? "Generated by AI. This is a very very very very very very very very very very very long banner message. " : "Generated by AI. "
        
        if self.messageType == .aiNotice {
            if self.withLink {
                Text("\(noticeText) with [link](https://www.sap.com)")
                    .accessibilityAddTraits(.isLink)
            } else if self.withAttachedAction {
                Text("\(noticeText)") + Text("View more").foregroundStyle(Color.preferredColor(.tintColor)).font(.fiori(forTextStyle: .footnote, weight: .semibold))
            } else {
                Text("\(noticeText)")
            }
        } else {
            if self.withLink {
                Text("\(text) with [link](https://www.sap.com)")
                    .accessibilityAddTraits(.isLink)
            } else if self.withAttachedAction {
                HStack {
                    Text("\(text)")
                    Button(action: {
                        print("Custom button tapped in title")
                    }, label: {
                        Text("Action")
                            .foregroundStyle(Color.preferredColor(.tintColor))
                    })
                    Spacer()
                }
            } else {
                Text("\(text)")
            }
        }
    }
    
    var body: some View {
        List {
            ForEach(0 ..< 6) { index in
                Text("cell at index: \(index)")
            }
            Button {
                withAnimation(.linear) {
                    self.show.toggle()
                }
            } label: {
                Text("Show / Hide")
            }
            
            Toggle("Push Content Down", isOn: self.$pushContentDown)
                .alignmentGuide(.listRowSeparatorLeading, computeValue: { _ in
                    0
                })
            Toggle("With Link", isOn: self.$withLink)
                .alignmentGuide(.listRowSeparatorLeading, computeValue: { _ in
                    0
                })
            Toggle("With Attached Action", isOn: self.$withAttachedAction)
                .alignmentGuide(.listRowSeparatorLeading, computeValue: { _ in
                    0
                })
            Toggle("Long Text", isOn: self.$withLongText)
                .alignmentGuide(.listRowSeparatorLeading, computeValue: { _ in
                    0
                })
            Picker("Message Type", selection: self.$messageType) {
                Text("neutral").tag(BannerMultiMessageType.neutral)
                Text("informative").tag(BannerMultiMessageType.informative)
                Text("aiNotice").tag(BannerMultiMessageType.aiNotice)
                Text("positive").tag(BannerMultiMessageType.positive)
                Text("critical").tag(BannerMultiMessageType.critical)
                Text("negative").tag(BannerMultiMessageType.negative)
                Text("offline").tag(BannerMultiMessageType.offline)
            }
            .alignmentGuide(.listRowSeparatorLeading, computeValue: { _ in
                0
            })
            Picker("Alignment", selection: self.$alignment) {
                Text("Leading").tag(0)
                Text("Center").tag(1)
            }
            .alignmentGuide(.listRowSeparatorLeading, computeValue: { _ in
                0
            })
            Toggle("Hides Close Action", isOn: self.$hidesCloseAction)
        }
        .bannerMessageView(isPresented: self.$show,
                           pushContentDown: self.$pushContentDown,
                           icon: {
                               if self.messageType == .aiNotice {
                                   Image(fioriName: "fiori.ai")
                                       .accessibilityLabel(Text("ai notice"))
                               } else {
                                   Image(systemName: "info.circle")
                                       .accessibilityLabel(Text("negative"))
                               }
                           },
                           title: {
                               self.titleView
                           }, bannerTapped: {
                               self.withAttachedAction && (self.messageType == .aiNotice) ? self.toggleShowSheet() : print("banner is tapped")
                           },
                           alignment: self.alignment == 1 ? .center : .leading,
                           hidesCloseAction: self.hidesCloseAction,
                           messageType: self.messageType)
        .navigationTitle("Banner Message")
        .sheet(isPresented: self.$showBottomSheet) {
            Text("detail information")
                .presentationDetents([.height(250), .medium])
                .presentationDragIndicator(.visible)
        }
    }
    
    func openURL() {
        let url = URL(string: "https://sap.com")!
        UIApplication.shared.open(url)
    }
    
    func toggleShowSheet() {
        self.showBottomSheet.toggle()
    }
}
