import Foundation
import SwiftUI

/**
 Components in this file will have `View` and `Style` definitions generated by Sourcery.
 */

// sourcery: BaseComponent
protocol _TitleComponent {
    // sourcery: @ViewBuilder
    var title: AttributedString { get }
}

// sourcery: BaseComponent
protocol _SubtitleComponent {
    // sourcery: @ViewBuilder
    var subtitle: AttributedString? { get }
}

// sourcery: BaseComponent
protocol _TagsComponent {
    // sourcery: resultBuilder.name = @TagBuilder, resultBuilder.backingComponent = TagStack
    var tags: [AttributedString] { get }
}

// sourcery: BaseComponent
protocol _FootnoteComponent {
    // sourcery: @ViewBuilder
    var footnote: AttributedString? { get }
}

// sourcery: BaseComponent
protocol _DescriptionComponent {
    // sourcery: @ViewBuilder
    var description: AttributedString? { get }
}

// sourcery: BaseComponent
protocol _StatusComponent {
    // sourcery: resultBuilder.name = @ViewBuilder, resultBuilder.backingComponent = TextOrIconView
    var status: TextOrIcon? { get }
}

// sourcery: BaseComponent
protocol _SubstatusComponent {
    // sourcery: resultBuilder.name = @ViewBuilder, resultBuilder.backingComponent = TextOrIconView
    var substatus: TextOrIcon? { get }
}

// sourcery: BaseComponent
protocol _DetailImageComponent {
    // sourcery: @ViewBuilder
    var detailImage: Image? { get }
}

// sourcery: BaseComponent
protocol _IconsComponent {
    // sourcery: resultBuilder.name = @IconBuilder, resultBuilder.backingComponent = IconStack
    var icons: [TextOrIcon] { get }
}

// sourcery: BaseComponent
protocol _FootnoteIconsComponent {
    // sourcery: resultBuilder.name = @FootnoteIconsBuilder, resultBuilder.backingComponent = FootnoteIconStack
    var footnoteIcons: [TextOrIcon] { get }
}

// sourcery: BaseComponent
protocol _AvatarsComponent {
    // sourcery: resultBuilder.name = @AvatarsBuilder, resultBuilder.backingComponent = AvatarStack
    var avatars: [TextOrIcon] { get }
}

// TODO: rename to _ActionComponent after resolving the conflict.
// sourcery: BaseComponent
protocol _NewActionComponent {
    // sourcery: @ViewBuilder
    var newAction: FioriButton? { get }
}

// sourcery: BaseComponent
protocol _SwitchComponent {
    // sourcery: @Binding
    var isOn: Bool { get }
}
