import Foundation
import SwiftUI

// MARK: NewTitleComponent

protocol NewTitleComponent {
    associatedtype Title: View
    @ViewBuilder
    var title: Title { get }
    
    // Define the name and type that will be used in data-based initilaizer generated by Swift Macro. Shouldn't be used by SDK developer.
    var titleText_: AttributedString { get }
}

// TODO: macro
extension NewTitleComponent {
    var titleText_: AttributedString {
        ""
    }
}

// MARK: NewSubtitleComponent

protocol NewSubtitleComponent {
    associatedtype Subtitle: View
    
    var subtitle: Subtitle { get }
    
    // Define the name and type that will be used in data-based initilaizer generated by Swift Macro. Shouldn't be used by SDK developer.
    var subtitleText_: AttributedString? { get }
}

// TODO: macro
extension NewSubtitleComponent {
    var subtitleText_: AttributedString? {
        nil
    }
}

// MARK: NewStatusComponent

protocol NewStatusComponent {
    associatedtype Status: View
    
    var status: Status { get }
    
    // Define the name and type that will be used in data-based initilaizer generated by Swift Macro. Shouldn't be used by SDK developer.
    var statusText_: AttributedString? { get }
}

// TODO: macro
extension NewStatusComponent {
    var statusText_: AttributedString? {
        nil
    }
}

// MARK: NewActionComponent

protocol NewActionComponent {
    associatedtype ActionTitle: View
    
    var actionTitle: ActionTitle { get }
    var action: (() -> Void)? { get }
    
    // Define the name and type that will be used in data-based initilaizer generated by Swift Macro. Shouldn't be used by SDK developer.
    var actionTitleText_: AttributedString? { get }
}

// TODO: macro
extension NewActionComponent {
    var actionTitleText_: AttributedString? {
        nil
    }
}
