configurations:
  - sources:
    - ./../Sources/FioriSwiftUICore/_ComponentProtocols
    templates:
      - stencils/ComponentTemplate.swifttemplate
    output:
      ./../Sources/FioriSwiftUICore/_generated
    args:
      selectedTypes: []

