
sources:
  - ./../Sources/FioriSwiftUICore/Components/
  - ./../Sources/FioriSwiftUICore/Models/
  - ./../Sources/FioriSwiftUICore/_generated/Components/
templates:
  - ./../sourcery/stencils/main_phase/model_decl.swifttemplate
output:
  swift_gen_temp/
args:
  prune: true
force-parse:
  - generated

