
sources:
  - ./../Sources/FioriSwiftUICore/Components/
templates:
  include:
    - ./../sourcery/stencils/pre_phase/
  exclude: # Sourcery treats all the templates as independent and so would generate files based on partial templates as well but we'll await this excluding those
    - ./../sourcery/stencils/pre_phase/partials/
output:
  ./../Sources/FioriSwiftUICore/_generated/Components
args:
  prune: true
