#!/bin/bash
# exclude files in Sources/FioriSwiftUICore/_generated/ (needed as exclude option in .swiftformat config file is not honored by git-format-staged)
npx git-format-staged --formatter 'swiftformat stdin --stdinpath "{}"' '*.swift' '!Sources/FioriSwiftUICore/_generated/*'
